services:
  - type: web
    name: fenmoai
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && cd server && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
